apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      maxLines: 1000
      timeout: 60

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        spanStartTimeShift: 5m
        spanEndTimeShift: -5m
        filterByTraceID: true
        filterBySpanID: true
      lokiSearch:
        datasourceUid: loki

  - name: App Postgres (via PgBouncer)
    uid: app-postgres
    type: postgres
    access: proxy
    url: pgbouncer:6432
    user: ${APP_DB_USER}
    secureJsonData:
      password: ${APP_DB_PASSWORD}
    jsonData:
      database: ${APP_DB}
      sslmode: disable
      postgresVersion: 1500   # PostgreSQL 15.x
      timescaledb: false
      maxOpenConns: 50        # optional tuning
      maxIdleConns: 10
      connMaxLifetime: 14400  # 4 hours in seconds
